version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    target-branch: "main"
    groups:
      docker-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    target-branch: "main"
    groups:
      github-actions-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "pip"
    target-branch: "main"
    groups:
      pip-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
